name: php

on: [push, pull_request]

jobs:  
  build:
    env:
      setup: 'basic'
      symfony: "*"  
    strategy:
      matrix:
        include:
          - php: 5.6
            setup: 'lowest'
            symfony: "^2.1"
          - php: 5.6
            setup: 'lowest' 
            symfony: "^3"
          - php: 7.1
            setup: 'lowest' 
            symfony: "^4"
          - php: 7.2
            setup: 'lowest' 
            symfony: "^5"
          - php: 7.3
            setup: 'lowest' 
            symfony: "^5"
          - php: 7.4
            setup: 'lowest' 
            symfony: "^5"
          - php: 8.0
            setup: 'lowest' 
            symfony: "^5"

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2   
      with:
        php-version: ${{ matrix.php }}
        extensions: mbstring, intl
        ini-values: post_max_size=256M, max_execution_time=180
        coverage: xdebug        
        tools: php-cs-fixer, phpunit:latest

    - name: Install dependencies (Symfony != '*')
      if: ${{ env.symfony != '*' }}
      run: composer require symfony/http-foundation:${{env.symfony}} --no-update --no-interaction
      
    - name: Install dependencies (Setup = basic)
      if: ${{ env.setup == 'basic' }}
      run: composer install --prefer-dist --no-interaction
      
    - name: Install dependencies (Setup = lowest)
      if: ${{ env.setup == 'lowest' }}
      run: composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable
      
    - name: Run PHPCS
      run: vendor/bin/phpcs --standard=PSR2 src/
      
    - name: Run PHPUnit
      run: vendor/bin/phpunit --coverage-text  --coverage-clover=coverage.clover
    
    - name: Get Scrutinizer
      run: wget https://scrutinizer-ci.com/ocular.phar
    
    - name: Upload results to Scrutinizer
      run: php ocular.phar code-coverage:upload --format=php-clover coverage.clover
